Param(
    [Parameter(Mandatory=$true)]
    [string]$Mode
)

$TMPDIR = "tmp"
$COMMAND = "..\..\build\bin\schema2code.exe"

# resolve mode
switch ($Mode) {
    "qt" {
        $env:PATH = "$env:GITHUB_WORKSPACE\ivef-sdk\build/targets/qt/lib;$env:PATH"
        $DATADIR = Join-Path $TMPDIR "qt"
        $REFDIR  = "ref\qt"
        $CommandArgs = @("--file=test.xsd", "--qt", "--out=$DATADIR", "--prefix=TST")
    }
    "objc" {
        $DATADIR = Join-Path $TMPDIR "objc"
        $REFDIR  = "ref\objc"
        $CommandArgs = @("--file=test.xsd", "--objc", "--out=$DATADIR", "--prefix=TST")
    }
    "java" {
        $DATADIR = Join-Path $TMPDIR "java"
        $REFDIR  = "ref\java"
        $CommandArgs = @("--file=test.xsd", "--java", "--out=$DATADIR", "--prefix=TST")
    }
    "php" {
        $DATADIR = Join-Path $TMPDIR "php"
        $REFDIR  = "ref\php"
        $CommandArgs = @("--file=test.xsd", "--php", "--out=$DATADIR", "--prefix=TST")
    }
    "all" {
        pwsh ./run_all_tests.ps1 php
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        pwsh ./run_all_tests.ps1 qt
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        pwsh ./run_all_tests.ps1 objc
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        pwsh ./run_all_tests.ps1 java
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        exit 0
    }
    Default {
        Write-Host "syntax: ./run_all_tests.ps1 [qt, objc, java, php, all]"
        exit 1
    }
}

# prepare directories
New-Item -ItemType Directory -Force -Path $DATADIR | Out-Null
New-Item -ItemType Directory -Force -Path $TMPDIR | Out-Null

# clean output folder
Get-ChildItem -Path $DATADIR -Recurse -Force -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse

# run schema2code
$ResultFile = Join-Path $TMPDIR "result.s2c"
& $COMMAND $CommandArgs | Out-File -FilePath $ResultFile -Encoding utf8
Get-Content $ResultFile

$DiffOut = Join-Path $TMPDIR "result.diff"
Remove-Item $DiffOut -Force -ErrorAction SilentlyContinue

# ignore pattern in generated files (e.g. timestamp)
$IgnoreRegex = "Generated by schema2code on .*"

function Convert-Content {
    param([string]$Path)
    return (Get-Content $Path | Where-Object { $_ -notmatch $IgnoreRegex })
}

# recursively compare
$refFiles = Get-ChildItem -Recurse $REFDIR | Where-Object { -not $_.PSIsContainer }
$errCount = 0

foreach ($ref in $refFiles) {
    $fullPath = $ref.FullName
    $genPath = $fullPath.Replace($REFDIR, $DATADIR)

    if (-not (Test-Path $genPath)) {
        Add-Content $DiffOut "Missing generated file: $genPath"
        $errCount++
        continue
    }

    $refLines = Convert-Content $ref.FullName
    $genLines = Convert-Content $genPath

    $diff = Compare-Object $refLines $genLines -SyncWindow 2

    if ($diff) {
        Add-Content $DiffOut "DIFF in file: $filename"
        Add-Content $DiffOut ($diff | Out-String)
        Add-Content $DiffOut "`n---`n"
        $errCount++
    }
}

# check for extra generated files not in ref
$genFiles = Get-ChildItem -Recurse $DATADIR | Where-Object { -not $_.PSIsContainer }
foreach ($gen in $genFiles) {
    $fullPath = $gen.FullName
    $refPath = $fullPath.Replace($DATADIR, $REFDIR)

    if (-not (Test-Path $refPath)) {
        Add-Content $DiffOut "Extra generated file not in reference: $filename"
        $errCount++
    }
}

if ($errCount -eq 0) {
    Write-Host "OK"
} else {
    Write-Host "NOK"
    Write-Host "---"
    Get-Content $DiffOut
    Write-Host "---"
    exit 1
}
