<?php

// 
//  Ping
//
//  Ping is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Ping is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY ); without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//*********************************************************************************
//  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
//  Generated by xsd2code on Fri May 28 20:19:56 2010.
//*********************************************************************************
//  Copyright 2010
//


class Ping { 

    var $m_timeStamp; // default value is uninitialized
    var $m_timeStampPresent;

    public function Ping() {

        date_default_timezone_set('UTC');
        $this->m_timeStampPresent = false;
    }

    public function setTimeStamp( $val ) {

        $this->m_timeStampPresent = true;
        $this->m_timeStamp = $val;
        return true;
    }

    public function getTimeStamp() {

        return $this->m_timeStamp;
    }

    public function toXML() {

        $xml = new SimpleXMLElement("<Ping></Ping>");

        if ( $this->m_timeStampPresent ) {
            $xml->addAttribute('TimeStamp', $this->m_timeStamp);
        } else { 
            return ""; // not all required attributes have been set 
        } 
        return $xml->asXML();
    }

    public function toString() {

    	return $this->toStringWithLead("");
    }

    public function toStringWithLead( $lead ) {

        $str = $lead . "Ping\n";

        $str .= $lead . "    TimeStamp = " . $this->m_timeStamp . "\n";

        return $str;
    }
}
?>
