<?php

// 
//  ServerStatus
//
//  ServerStatus is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ServerStatus is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY ); without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//*********************************************************************************
//  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
//  Generated by xsd2code on Fri May 28 20:19:56 2010.
//*********************************************************************************
//  Copyright 2010
//


class ServerStatus { 

    var $m_status; // default value is uninitialized
    var $m_statusPresent;
    var $m_details; // default value is uninitialized
    var $m_detailsPresent;

    public function ServerStatus() {

        date_default_timezone_set('UTC');
        $this->m_statusPresent = false;
        $this->m_detailsPresent = false;
    }

    public function setStatus( $val ) {

        if ( ( $val != "queuefull" ) &&
             ( $val != "ok" ) )
            return false;
        $this->m_statusPresent = true;
        $this->m_status = $val;
        return true;
    }

    public function getStatus() {

        return $this->m_status;
    }

    public function setDetails( $val ) {

        $this->m_detailsPresent = true;
        $this->m_details = $val;
        return true;
    }

    public function getDetails() {

        return $this->m_details;
    }

    public function hasDetails() {

        return $this->m_detailsPresent;
    }

    public function toXML() {

        $xml = new SimpleXMLElement("<ServerStatus></ServerStatus>");

        if ( $this->m_statusPresent ) {
            $xml->addAttribute('Status', $this->m_status);
        } else { 
            return ""; // not all required attributes have been set 
        } 
        if ( $this->hasDetails() ) {
            $xml->addAttribute('Details', $this->m_details);
        }
        return $xml->asXML();
    }

    public function toString() {

    	return $this->toStringWithLead("");
    }

    public function toStringWithLead( $lead ) {

        $str = $lead . "ServerStatus\n";

        $str .= $lead . "    Status = " . $this->m_status . "\n";
        if ( $this->hasDetails() ) {
            $str .= $lead . "    Details = " . $this->m_details . "\n";
        }

        return $str;
    }
}
?>
