/* 
 *  ForeignId
 *
 *  ForeignId is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Foobar is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY ); without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 **********************************************************************************
 *  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
 *  Generated by xsd2code on Thu Sep 4 16:29:00 2008.
 **********************************************************************************
 *  Copyright 2008
 *
 */

#ifndef __FOREIGNID_H__
#define __FOREIGNID_H__

#include <QtCore>

class ForeignId : public QObject { 
    Q_OBJECT

public:
    ForeignId();
    ForeignId(const ForeignId&);
    ForeignId & operator=(const ForeignId&/*val*/);

    /* Id:
       Name of the Identifier */
    void setId(QString val);
    QString getId() const;

    /* Value:
       Value of the identifier */
    void setValue(QString val);
    QString getValue() const;
    QString toXML();
    QString toString(QString lead);

private:
    QString m_id;
    QString m_value;

}; 

#endif

