/* 
 *  Header
 *
 *  Header is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Foobar is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY ); without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 **********************************************************************************
 *  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
 *  Generated by xsd2code on Thu Sep 4 16:29:00 2008.
 **********************************************************************************
 *  Copyright 2008
 *
 */

#ifndef __HEADER_H__
#define __HEADER_H__

#include <QtCore>

class Header : public QObject { 
    Q_OBJECT

public:
    Header();
    Header(const Header&);
    Header & operator=(const Header&/*val*/);

    /* Version:
       Defines the version of the protocol used. Syntax is major.minor.patch patch releases fix only bugs, minor releases may add functionality but are compatible, major releases are not compatible */
    void setVersion(QString val);
    QString getVersion() const;

    /* MsgRefId:
       Must be an Universally Unique Identifier for each message  (TU-T Rec. X.667 | ISO/IEC 9834-8.) Reply messages refer to this id to identify the message they are replying to */
    void setMsgRefId(QString val);
    QString getMsgRefId() const;
    QString toXML();
    QString toString(QString lead);

private:
    QString m_version;
    QString m_msgRefId;

}; 

#endif

