/* 
 *  Propulsion
 *
 *  Propulsion is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Foobar is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY ); without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 **********************************************************************************
 *  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
 *  Generated by xsd2code on Thu Sep 4 16:29:01 2008.
 **********************************************************************************
 *  Copyright 2008
 *
 */

#ifndef __PROPULSION_H__
#define __PROPULSION_H__

#include <QtCore>

class Propulsion : public QObject { 
    Q_OBJECT

public:
    Propulsion();
    Propulsion(const Propulsion&);
    Propulsion & operator=(const Propulsion&/*val*/);

    /* Power:
       The power of this engine in HP */
    void setPower(float val);
    float getPower() const;

    /* MainEngine:
       Indicates whether this engine the main engine */
    void setMainEngine(bool val);
    bool getMainEngine() const;
    QString toXML();
    QString toString(QString lead);

private:
    float m_power;
    bool m_mainEngine;

}; 

#endif

