/* 
 *  XMLChart
 *
 *  XMLChart is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Foobar is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY ); without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 **********************************************************************************
 *  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
 *  Generated by xsd2code on Thu Sep 4 16:29:01 2008.
 **********************************************************************************
 *  Copyright 2008
 *
 */

#ifndef __XMLCHART_H__
#define __XMLCHART_H__

#include <QtCore>
#include "IVEF2area.h"

class XMLChart : public QObject { 
    Q_OBJECT

public:
    XMLChart();
    XMLChart(const XMLChart&);
    XMLChart & operator=(const XMLChart&/*val*/);
    void addArea(Area val);
    Area getAreaAt(int i) const;
    int countOfAreas() const;

    /* Name:
       Name of the chart */
    void setName(QString val);
    QString getName() const;
    QString toXML();
    QString toString(QString lead);

private:
    QVector<Area> m_areas;
    QString m_name;

}; 

#endif

