<?php

// 
//  ObjectDatas
//
//  ObjectDatas is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ObjectDatas is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY ); without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//*********************************************************************************
//  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
//  Generated by xsd2code on Thu Aug 26 11:51:17 2010.
//*********************************************************************************
//  Copyright 2010
//

require_once "IVEFObjectData.php";

class ObjectDatas { 

    var $m_objectData; // default value is uninitialized
    var $m_objectDataPresent;

    public function ObjectDatas() {

        date_default_timezone_set('UTC');
        $this->m_objectDataPresent = false;
        $this->m_objectDatas = array();
    }

    public function removeObjectData(ObjectData $val ) {
          for($i=0; $i< count($this->m_objectDatas); $i++) {
             if($this->m_objectDatas[i] == $val) {
                 unset($this->m_objectDatas[i]);
             }
          }
        return true;
    }

    public function addObjectData(ObjectData $val ) {

        $this->m_objectDatas[] = $val;
        return true;
    }

    public function getObjectDataAt($i) {

        return $this->m_objectDatas[$i];
    }

    public function countOfObjectDatas() {

        return count($this->m_objectDatas);
    }

    public function toXML() {

        $xml = new SimpleXMLElement("<ObjectDatas></ObjectDatas>");

        foreach($this->m_objectDatas as $attribute) {
        $dom = dom_import_simplexml($xml);
        $child_as_xml = $attribute->toXML();
        $child_as_simplexml = new SimpleXMLElement($child_as_xml);
        $child_as_dom = dom_import_simplexml($child_as_simplexml);
        $child_as_leaf = $dom->ownerDocument->importNode($child_as_dom, true);
        $dom->appendChild($child_as_leaf);
        $xml = simplexml_import_dom($dom);
        } 
        return $xml->asXML();
    }

    public function toString() {

    	return $this->toStringWithLead("");
    }

    public function toStringWithLead( $lead ) {

        $str = $lead . "ObjectDatas\n";

        foreach($this->m_objectDatas as $attribute) {
           $str .= $attribute->toStringWithLead($lead . "    ");
        }

        return $str;
    }
}
?>
