/* 
 *  Pong
 *
 *  Pong is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Foobar is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY ); without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 **********************************************************************************
 *  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
 *  Generated by xsd2code on Mon Apr 26 22:36:23 2010.
 **********************************************************************************
 *  Copyright 2010
 *
 */

package ivef;

import java.util.*;
import java.text.DecimalFormat;
import java.text.DateFormat;
import java.text.SimpleDateFormat;


public class Pong { 

    private Date m_timeStamp; // default value is uninitialized
    private boolean m_timeStampPresent;
    private String m_msgId; // default value is uninitialized
    private boolean m_msgIdPresent;
    private int m_sourceId; // default value is uninitialized
    private boolean m_sourceIdPresent;

    public Pong() {

        m_timeStampPresent = false;
        m_msgIdPresent = false;
        m_sourceIdPresent = false;
    }

    public Pong(Pong val) {

        m_timeStamp = val.getTimeStamp();
        if (val != null) {
            m_timeStampPresent = true;
        }
        m_msgId = val.getMsgId();
        if (val != null) {
            m_msgIdPresent = true;
        }
        m_sourceId = val.getSourceId();
        if (val != null) {
            m_sourceIdPresent = true;
        }
    }

    public boolean setTimeStamp(Date val) {

        m_timeStampPresent = true;
        m_timeStamp = val;
          return true;
    }

    public Date getTimeStamp() {

        return m_timeStamp;
    }

    public boolean setMsgId(String val) {

        m_msgIdPresent = true;
        m_msgId = val;
          return true;
    }

    public String getMsgId() {

        return m_msgId;
    }

    public boolean setSourceId(int val) {

        m_sourceIdPresent = true;
        m_sourceId = val;
          return true;
    }

    public int getSourceId() {

        return m_sourceId;
    }

    public String toXML() {

        String xml = "<Pong";
        String dataMember;        DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
        DecimalFormat nf = new DecimalFormat("0.000000");

        if ( m_timeStampPresent ) {
            xml += " TimeStamp=\"" + df.format(m_timeStamp) + "\"";
        } else { 
            return null; // not all required attributes have been set 
        } 
        if ( m_msgIdPresent ) {
            xml += " MsgId=\"" + encode( m_msgId) + "\"";
        } else { 
            return null; // not all required attributes have been set 
        } 
        if ( m_sourceIdPresent ) {
            xml += " SourceId=\"" + m_sourceId + "\"";
        } else { 
            return null; // not all required attributes have been set 
        } 
        xml += "/>\n";
        return xml;
    }

    public String toString(String lead) {

        String str = lead + "Pong\n";
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
        DecimalFormat nf = new DecimalFormat("0.000000");

        str +=  lead + "    TimeStamp = " + df.format(m_timeStamp) + "\n";
        str +=  lead + "    MsgId = " + m_msgId + "\n";
        str +=  lead + "    SourceId = " + m_sourceId + "\n";
        return str;
    }
    public String encode( String str) {

        str = str.replaceAll("&", "&amp;");
        str = str.replaceAll("<", "&lt;");
        str = str.replaceAll(">", "&gt;");
        str = str.replaceAll("\"", "&quot;");
        return str;
    }


}
