TMPDIR=tmp

COMMAND='../../build/bin/schema2code --file=test.xsd'
if [ "$1" == "qt" ]
then
    DATADIR=$TMPDIR/qt
    REFDIR=ref/qt
    ARGS="--qt --out=$DATADIR --prefix=TST"
elif [ "$1" == "objc" ]
then
    DATADIR=$TMPDIR/objc
    REFDIR=ref/objc
    ARGS="--objc --out=$DATADIR --prefix=TST"
elif [ "$1" == "java" ]
then
    DATADIR=$TMPDIR/java
    REFDIR=ref/java
    ARGS="--java --out=$DATADIR --prefix=TST"
elif [ "$1" == "php" ]
then
    DATADIR=$TMPDIR/php
    REFDIR=ref/php
    ARGS="--php --out=$DATADIR --prefix=TST"
elif [ "$1" == "all" ]
then
    # recursive call of ourselfs
    $0 php
    $0 qt
    $0 objc
    $0 java
    exit 0
else
    echo "syntax $0 [qt | objc | java | php | all]"
    exit 1
fi

mkdir -p $DATADIR
rm -Rf $DATADIR/*

$COMMAND $ARGS > $TMPDIR/result.s2c

diff -I "  Generated by schema2code on .*" -r --suppress-common-lines -y ${REFDIR} ${DATADIR} > $TMPDIR/result.diff
if [ $? == 0 ] 
then 
    echo OK
else
    echo NOK
    echo ---
    cat $TMPDIR/result.diff
    echo ---
    exit 1
fi

# all test ok, clean up
####rm -Rf $TMPDIR
