/* 
 *  ILLoginResponse
 *
 *  ILLoginResponse is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Foobar is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY ); without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 **********************************************************************************
 *  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
 *  Generated by xsd2code on Tue Jan 5 23:01:06 2010.
 **********************************************************************************
 *  Copyright 2009
 *
 */

#import <Foundation/Foundation.h>

@interface ILLoginResponse : NSObject { 
    NSString *m_reason;
    bool m_reasonPresent;
    NSString *m_responseOn;
    int m_result;
}


/* Reason:
   String describing reason for declining, only used when result is "Declined" */
-(void) setReason:(NSString *) val;
-(NSString *) reason;
-(bool) hasReason;

/* ResponseOn:
   Corresponds to the original MsgRefId from the Login.xml message. Must be an Universally Unique Identifier (TU-T Rec. X.667 | ISO/IEC 9834-8.) */
-(void) setResponseOn:(NSString *) val;
-(NSString *) responseOn;

/* Result:
   1 = Accepted 2 = Declined */
-(void) setResult:(int) val;
-(int) result;

-(void) setAttributes:(NSDictionary *)attributeDict;
-(NSDictionary *) attributes;
-(NSString *) XML;
-(NSString *) stringValue;
-(NSString *) stringValueWithLead:(NSString *) lead;
-(NSString *) encode: (NSString *) input;

@end



