/* 
 *  TSTParser
 *
 *  TSTParser is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Foobar is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY ); without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 **********************************************************************************
 *  WARNING: THIS CODE WAS GENERATED DO NOT MODIFY, CHANGE THE XSD INSTEAD
 *  Generated by schema2code on Tue Jan 8 23:30:40 2013.
 **********************************************************************************
 *  Copyright 2010
 *
 */

#import <Foundation/Foundation.h>
#import "TSTSchema.h"
#import "TSTMSG_Notification.h"
#import "TSTMessage.h"
#import "TSTArgument.h"
#import "TSTEvent.h"
#import "TSTAreaName.h"

//-----------------------------------------------------------
//! \brief       Class definition of TSTParser
//!
@interface TSTParser : NSObject { 
    NSMutableString *m_dataBuffer;
    NSMutableString *m_characterBuffer;
    NSMutableArray *m_objStack;
    NSMutableArray *m_closeTags;
}

//!Delegate method for NSXMLParser
//!
- (void)     parser:(NSXMLParser *)parser 
    didStartElement:(NSString *)elementName
       namespaceURI:(NSString *)namespaceURI
      qualifiedName:(NSString *)qualifiedName
         attributes:(NSDictionary *)attributeDict;
//!Delegate method for NSXMLParser
//!
- (void)parser:(NSXMLParser *)parser foundCharacters:(NSString *)string;
//!Delegate method for NSXMLParser
//!
- (void)     parser:(NSXMLParser *)parser 
      didEndElement:(NSString *)elementName
       namespaceURI:(NSString *)namespaceURI
      qualifiedName:(NSString *)qualifiedName;
- (BOOL) parseXMLString:(NSString *)data andBuffer: (BOOL) cont;
- (void)parser:(NSXMLParser *)parser parseErrorOccurred:(NSError *)parseError;
//!Published Notifications
//!
//    @"NewTSTMSG_Notification" with @"Data" = TSTMSG_Notification
//    @"NewTSTArgument" with @"Data" = TSTArgument
//    @"NewTSTAreaName" with @"Data" = TSTAreaName
//    @"ILParserError" with @"Error" = NSError 
//    @"ILValidationError" with @"Error" = NString 

@end



